<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

/**
 * Fires at start of header.php, immediately before `genesis_title` action hook to render the Doctype content.
 *
 * @since 1.3.0
 */
do_action( 'genesis_doctype' );

/**
 * Fires immediately after `genesis_doctype` action hook, in header.php to render the document title.
 *
 * @since 1.0.0
 */
do_action( 'genesis_title' );

/**
 * Fires immediately after `genesis_title` action hook, in header.php to render the meta elements.
 *
 * @since 1.0.0
 */
do_action( 'genesis_meta' );

wp_head(); // We need this for plugins.
?>
</head>
<?php if( get_field('background_color_heading') ): ?>
	<style type="text/css">
		.header-main{ background: <?php the_field('background_color_heading'); ?>; }
		.header-main .header-socials .wrap a{ color: <?php the_field('background_color_heading'); ?>; }
	</style>
<?php endif; ?>
<?php if( get_field('padding_top_site_inner') ): ?>
	<style type="text/css">
		body.elementor-template-full-width .site-inner{ padding-top: 0px; }
	</style>
<?php endif; ?>
<?php if( get_field('header_position_absolute_transparent') ): ?>
	<style type="text/css">
	.header-main {
		position: absolute;
		width: 100%;
		background: transparent !important;
	}
	.header-main .header-socials .wrap a {
	    z-index: 9;
	}
	.header-main .site-header .title-area{
	    z-index: 9;
	}
	.header-main .header-socials .wrap a {
		background: transparent;
		color: #fff;
	}
	.header-main .header-socials .wrap a .fa:before {
    	font-size: 17px;
	}
	body .site-inner {
		padding: 0 !important;
	}
	</style>
<?php endif; ?>
<?php
genesis_markup(
	[
		'open'    => '<body %s>',
		'context' => 'body',
	]
);

if ( function_exists( 'wp_body_open' ) ) {
	wp_body_open();
}
/**
 * Fires immediately after the `wp_body_open` action hook.
 *
 * @since 1.0.0
 */
do_action( 'genesis_before' );

genesis_markup(
	[
		'open'    => '<div %s>',
		'context' => 'site-container',
	]
);

// button share in pages
share_page_button();

// alert banner top page
alert_banner_top();

genesis_markup(
	[
		'open'    => '<div %s>',
		'context' => 'header-main',
	]
);
/**
 * Fires immediately after the site container opening markup, before `genesis_header` action hook.
 *
 * @since 1.0.0
 */
do_action( 'genesis_before_header' );

/**
 * Fires to display the main header content.
 *
 * @since 1.0.2
 */
do_action( 'genesis_header' );
/**
 * Fires immediately after the `genesis_header` action hook, before the site inner opening markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after_header' );

genesis_markup(
	[
		'close'   => '</div>',
		'context' => 'header-main',
	]
);


// FAI confirmation popup: render only on insurer templates or selected pages (ACF option 'fai_confirmation_popup')
$fai_popup = function_exists('get_field') ? (array) get_field('fai_confirmation_popup', 'option') : [];
$fai_target_pages = isset($fai_popup['show_this_popup_at']) ? (array) $fai_popup['show_this_popup_at'] : [];
$fai_heading = isset($fai_popup['heading']) && $fai_popup['heading'] ? $fai_popup['heading'] : 'Thank you for visiting Find an Insurer';
$fai_items = isset($fai_popup['checklist_items']) && is_array($fai_popup['checklist_items']) ? $fai_popup['checklist_items'] : [];
$fai_validation_message = isset($fai_popup['validation_message']) && $fai_popup['validation_message'] ? $fai_popup['validation_message'] : 'You must tick all fields before continuing';
$is_insurer_context = ( function_exists('is_singular') && is_singular('insurer') )
	|| ( function_exists('is_post_type_archive') && is_post_type_archive('insurer') )
	|| ( function_exists('is_tax') && is_tax('insurer-category') );
$is_target_page = function_exists('is_page') ? is_page($fai_target_pages) : false;
$should_render_fai_popup = $is_insurer_context || $is_target_page;

if ( $should_render_fai_popup ) : ?>
	<div id="fai-confirmation-popup" aria-hidden="true" role="dialog">
		<div class="fai-popup-backdrop"></div>
		<div class="fai-popup-dialog" role="document" aria-modal="true">
			<div class="fai-popup-header">
				<div class="fai-popup-logo">
					<a href="<?php echo esc_url(home_url('/')); ?>">
						<img src="/wp-content/themes/genesis-insuranceca/package-main/assets/images/logo-green.svg" alt="Find an Insurer Logo">
					</a>
				</div>
			</div>
			<div class="fai-popup-body">
				<h2><?php echo esc_html($fai_heading); ?></h2>
				<?php if (!empty($fai_items)) : ?>
					<?php foreach ($fai_items as $idx => $row) :
						$text = isset($row['checkbox']) ? trim(wp_strip_all_tags($row['checkbox'])) : '';
						if (!$text) { continue; }
						$input_id = 'fai_chk_' . intval($idx);
					?>
					<label class="fai-check" for="<?php echo esc_attr($input_id); ?>">
						<input type="checkbox" id="<?php echo esc_attr($input_id); ?>">
						<span class="fai-box" aria-hidden="true"></span>
						<span class="fai-label"><?php echo esc_html($text); ?></span>
					</label>
					<?php endforeach; ?>
				<?php endif; ?>
				<button type="button" id="fai_btn_continue" class="button button-primary" aria-disabled="true">Continue</button>
				<p class="fai-required">* Required field</p>
				<p class="fai-error" aria-live="polite" style="display:none;"><?php echo esc_html($fai_validation_message); ?></p>
			</div>
		</div>
	</div>
<?php endif; ?>

<?php
genesis_markup(
	[
		'open'    => '<div %s>',
		'context' => 'site-inner',
	]
);
genesis_structural_wrap( 'site-inner' );
